language: erlang
otp_release:
  - 19.0

# It would be possible to use the container-based infrastructure if
# it ran trusty. However, it doesn't and wget is too old to use for
# HTTPS to buildroot.net.
sudo: required
dist: trusty

# Install dependencies
addons:
  apt:
    packages:
    - bc
    - libssl-dev

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

env:
  - NERVES_TARGET=orangepi_zero CI_SYSTEM_NAME=nerves_system_$NERVES_TARGET REPO=$TRAVIS_REPO_SLUG NERVES_SYSTEM_CACHE=none NERVES_SYSTEM_COMPILER=local NERVES_PACKAGE=`pwd`

before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - git checkout v1.4.2
  - make clean
  - make
  - cd ..

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - mix compile
  # Testing should be moved to locally execute mix test.
  #  This will centralize the test suite for systems to the nerves package
  #  Removing these for now
  # - export NERVES_SYSTEM=$NERVES_PACKAGE/_build/dev/nerves/system
  # - export NERVES_TOOLCHAIN=$NERVES_PACKAGE/_build/dev/nerves/toolchain
  # - git clone https://github.com/nerves-project/nerves-examples
  # - cd nerves-examples/hello_gpio
  # - MIX_ENV=travis mix deps.get
  # - MIX_ENV=travis mix compile
  # - MIX_ENV=travis mix firmware

# Deploy the build products
before_deploy:
    - cd $NERVES_PACKAGE/.nerves/artifacts/*
    - ls
    - make system
    - cd $NERVES_PACKAGE
    - $NERVES_PACKAGE/deps/nerves_system_br/scripts/ci-deploy.sh

deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key:
      secure: W+WFey5H904nQEKhfH4OJ7KvLrD9vylzmiQj753vU5gqoCGRbGAZY/Y1kIc8vsOsq5oK2sKFJCUC6x/n0YLTYBQDTSWgC5ynL9Ve5ekOUKfg9/cXUSwWZfDLr0CxesES/jPRsm90yGd62e/OQ55nrvFRPaoifw9ol5HeLqYkTsxcvUBTY13f7fPdrl+j4qqhW1Upunu1cRdIqxUC7eU6hF6tpKCUkSb9gbGDTBO1n7b89mZ5hC4/Y6cbZ9rZxRUfHb1lY9rGwFxE46GRCftcfslwS/i/6ZR+9/1sszkA9TvxG1NnJXkV0M3jv5H7Y9qecJxJ4OJgOEVDzZHDS9GdpOLIHhGSzf1wWsayYZOvQAtC1/eMM+xWXZPX8lJrpoWYb4SgPuZbDhTap48LsaQEJSfwtsUKAAK2z4GBYrDzh83+rrexXTCQQT79bvUiAUXYxROVmQYVUw93488Jzztof4vt1Y6t0oGK1rXUXRxQjROsQYLXisdNypvnP8K7tyCDjgaRvOWvlXHQPCyg9kNjx7EQNfog7ZjeFHb1dwPjTNWbO3PCXsZbOz5CSlCDl5m7Ed6tTgy6K1NWO+rmGducZBZ9veP8FW+J+7Udjld3ZX5VhMvBLhrwjYr1Dtv3g+c5ER8HmnuASjP9ifn/Y19NHMXOl4nxTKuO4hksz8E0w7A=
    file:
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.tar.gz"
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.fw"
    skip_cleanup: true
    overwrite: true
    on:
      repo: $REPO
      tags: true
  # - provider: s3
  #   access_key_id: $S3_ID
  #   secret_access_key: $S3_KEY
  #   bucket: $S3_BUCKET
  #   skip_cleanup: true
  #   local_dir: artifacts
  #   upload-dir: test
  #   acl: public_read
  #   on:
  #     repo: $REPO
  #     all_branches: true

# Display build log on failure
after_failure:
    - tail -n 1000 $NERVES_PACKAGE/build.log
